@Library('devops-jenkins-shared-library') _

pipeline {
    agent any

    environment {
        REGISTRY = 'ghcr.io'
        GITHUB_REPO = 'https://github.com/DucThanhDao/Devops.git'
        GITHUB_BRANCH = 'feat/CI-CD-integration'
    }

    stages {
        stage('Checkout') {  
          steps {  
            git(  
              url: GITHUB_REPO,  
              credentialsId: 'github-pat',  
              branch: GITHUB_BRANCH  
            )  
          }  
        }  
        stage('Build Docker Image') {
            steps {
                script {
                    // Build the Docker image
                    def buildInfo = dockerBuild(
                        repository: GITHUB_BRANCH,
                        dockerfile: './microservice/company-website/Dockerfile'
                    )
                    echo "Built image: ${buildInfo.imageTag}"

                    // Store the image and tag for later use
                    env.IMAGE_TAG = buildInfo.imageTag
                    env.IMAGE_OBJECT = buildInfo.image
                }
            }
        }

        stage('Push Docker Image') {
            when {
                expression { env.REGISTRY != null && env.REGISTRY != '' }
            }
            steps {
                script {
                    // Push the Docker image to the registry
                    dockerPush(
                        registry: env.REGISTRY,
                        credentialsId: 'github-credential',
                        image: env.IMAGE_OBJECT,
                        imageTag: env.IMAGE_TAG
                    )
                }
            }
        }
    }
}