name: Deploy to Contabo Production
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Release Branch (eg. main)"
        required: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-image:
    name: Build Image
    uses: ./.github/workflows/shared-build-docker-image.yml
    with:
      branch_name: ${{ github.event.inputs.branch }}
    secrets:
      aws_region: ${{ secrets.AWS_REGION }}
      docker_registry_token: ${{ secrets.GHCR_TOKEN }}
      docker_registry_username: ${{ secrets.GHCR_USERNAME }}
      next_public_strapi_cms_api: ${{ secrets.NEXT_PUBLIC_STRAPI_CMS_API }}
      aws_oidc_role_arn: ${{ secrets.AWS_OIDC_ROLE_ARN }}
      s3_bucket_name: ${{ secrets.S3_BUCKET_NAME }}
      port: ${{ secrets.PORT }}
      node_env: ${{ secrets.NODE_ENV }}
      next_public_cdn_url: ${{ secrets.NEXT_PUBLIC_CDN_URL }}

  deploy:
    name: Deploy apps
    needs: [build-image]
    uses: ./.github/workflows/share-deploy-using-ssh.yml
    with:
      image_package: ${{ needs.build-image.outputs.image_package }}
      branch_name: ${{ github.event.inputs.branch }}
    secrets:
      docker_registry_token: ${{ secrets.GHCR_TOKEN }}
      docker_registry_username: ${{ secrets.GHCR_USERNAME }}
      ssh_host: ${{ secrets.CONTABO_SSH_HOST }}
      ssh_private_key: ${{ secrets.CONTABO_SSH_PRIVATE_KEY }}
      ssh_username: ${{ secrets.CONTABO_SSH_USERNAME }}
