pipeline {
    agent any

    environment {
        // Define environment variables for SSH credentials
        SSH_USERNAME = 'ubuntu'
        SSH_SERVER = 'dayoneteams.com'
        // AWS ENVs
        AWS_ROLE_SESSION_NAME = 'JenkinsSession'
        AWS_ROLE_SESSION_DURATION = 3600
    }

    stages {
        stage('Setup SSH Credentials with Credentials Binding') {
            steps {
                script {
                    // Use the sshUserPrivateKey binding to securely load the SSH key
                    withCredentials([sshUserPrivateKey(
                        credentialsId: 'dayone-ssh-credential',
                        keyFileVariable: 'SSH_KEY_FILE',
                        usernameVariable: 'SSH_USERNAME',
                        passphraseVariable: 'SSH_PASSPHRASE'
                    )]) {
                        // Use the SSH key to connect to a remote server
                        sh '''
                            ssh -i "${SSH_KEY_FILE}" -o StrictHostKeyChecking=no ${SSH_USERNAME}@${SSH_SERVER} "echo \\"Connected successfully!\\""
                        '''
                    }
                }
            }
        }
        stage('Setup SSH Credentials with ssh agent') {
            steps {
                script {
                    sshagent(['dayone-ssh-credential']) {
                        sh '''
                            ssh -o StrictHostKeyChecking=no ${SSH_USERNAME}@${SSH_SERVER} "echo \\"Connected successfully!\\""
                        '''
                    }
                }
            }
                
        }
        // Pending
        // stage('Setup AWS Credentials with Credentials Binding') {
        //     steps {
        //         script {
        //             // Use the aws binding to securely load AWS credentials
        //             withCredentials([aws(
        //                 credentialsId: 'aws-thanhdao-credential',
        //                 accessKeyVariable: 'AWS_ACCESS_KEY_ID',
        //                 secretKeyVariable: 'AWS_SECRET_ACCESS_KEY',
        //                 roleArn: 'AWS_ROLE_ARN',
        //                 roleSessionName: env.AWS_ROLE_SESSION_NAME,
        //                 roleSessionDurationSeconds: env.AWS_ROLE_SESSION_DURATION
        //             )]) {
        //                 // Use AWS CLI to interact with AWS services
        //                 sh '''
        //                     # Verify AWS credentials
        //                     aws sts get-caller-identity
        //                 '''

        //                 // Example: Assume the IAM role and perform actions
        //                 sh '''
        //                     # Assume the IAM role and list EC2 instances
        //                     aws sts assume-role \
        //                         --role-arn ${env.AWS_ROLE_ARN} \
        //                         --role-session-name ${env.AWS_ROLE_SESSION_NAME} \
        //                         --duration-seconds ${env.AWS_ROLE_SESSION_DURATION} \
        //                 '''
        //             }
        //         }
        //     }
        // }
    }
}